gpanel_route:
    resource: "@TechGSfBaseprjBundle/Resources/config/gPanel/routing.yml"
    prefix:   /gPanel    
    
########################################################################################
# Sezione FRAGMENT
########################################################################################

# FRAGMENT SESSIONE
