parameters:
#    tech_g_sf_baseprj.example.class: TechG\Bundle\SfBaseprjBundle\Example


services:
#    tech_g_sf_baseprj.example:
#        class: %tech_g_sf_baseprj.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    techg.kernel:
        class:     TechG\Bundle\SfBaseprjBundle\Extensions\MainKernel
        arguments: [@service_container]       
        
    twig.extension.appfwKernel:
        class: TechG\Bundle\SfBaseprjBundle\Twig\Extensions\MainKernelExtension
        arguments: [@techg.kernel]
        tags:
            - { name: twig.extension }
            
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }            


################# EVENTS LISTER #####################
            
    tech_g_sf_baseprj.kernel.init:
        class: TechG\Bundle\SfBaseprjBundle\Listener\TechgActionListener
        arguments: [ @techg.kernel ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onInitEvent, priority: 64 }

    tech_g_sf_baseprj.kernel.request:
        class: TechG\Bundle\SfBaseprjBundle\Listener\TechgActionListener
        arguments: [ @techg.kernel ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRequestEvent, priority: 0 }

    tech_g_sf_baseprj.kernel.exception:
        class: TechG\Bundle\SfBaseprjBundle\Listener\TechgActionListener
        arguments: [ @techg.kernel ]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }            

    tech_g_sf_baseprj.kernel.controller:
        class: TechG\Bundle\SfBaseprjBundle\Listener\TechgActionListener
        arguments: [ @techg.kernel ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }                        

    tech_g_sf_baseprj.kernel.view:
        class: TechG\Bundle\SfBaseprjBundle\Listener\TechgActionListener
        arguments: [ @techg.kernel ]
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView }                        

    tech_g_sf_baseprj.kernel.response:
        class: TechG\Bundle\SfBaseprjBundle\Listener\TechgActionListener
        arguments: [ @techg.kernel ]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }                        

    tech_g_sf_baseprj.kernel.terminate:
        class: TechG\Bundle\SfBaseprjBundle\Listener\TechgActionListener
        arguments: [ @techg.kernel ]
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }                        
            