parameters:
#    tech_g_sf_baseprj.example.class: TechG\Bundle\SfBaseprjBundle\Example


services:
#    tech_g_sf_baseprj.example:
#        class: %tech_g_sf_baseprj.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    techg.kernel:
        class:     TechG\Bundle\SfBaseprjBundle\Extensions\MainKernel
        arguments: [@service_container]       
        
    twig.extension.appfwKernel:
        class: TechG\Bundle\SfBaseprjBundle\Twig\Extensions\MainKernelExtension
        arguments: [@techg.kernel]
        tags:
            - { name: twig.extension }
            
    tech_g_sf_baseprj.onRequest_listener:
        class: TechG\Bundle\SfBaseprjBundle\Listener\AppOnRequestListener
        arguments: [ @techg.kernel ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRequestEvent }              