parameters:
#    tech_g_sf_baseprj.example.class: TechG\Bundle\SfBaseprjBundle\Example


services:
#    tech_g_sf_baseprj.example:
#        class: %tech_g_sf_baseprj.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
            
            
################ TECHG KERNEL SERVICES #####################            

    techg.settings:
        class:     TechG\Bundle\SfBaseprjBundle\Extensions\Setting\SettingManager
        arguments: [@service_container]       

    techg.debug:
        class:     TechG\Bundle\SfBaseprjBundle\Extensions\Debug\DebugManager
        arguments: [@service_container, @techg.settings]       

    techg.log:
        class:     TechG\Bundle\SfBaseprjBundle\Extensions\Log\LogManager
        arguments: [@service_container, @techg.settings]       

    techg.geocoder:
        class:     TechG\Bundle\SfBaseprjBundle\Extensions\Geocode\GeocoderManager
        arguments: [@service_container, @techg.settings]       
        
    techg.locale:
        class:     TechG\Bundle\SfBaseprjBundle\Extensions\Locale\LocaleManager
        arguments: [@service_container, @techg.settings]       
        
    techg.gpanel:
        class:     TechG\Bundle\SfBaseprjBundle\Extensions\GPanel\GPanelManager
        arguments: [@service_container, @techg.settings]       
        
    techg.mobiledetect:
        class:     TechG\Bundle\SfBaseprjBundle\Extensions\Mobiledetect\MobiledetectManager
        arguments: [@service_container, @techg.settings]       
        
    techg.kernel:
        class:     TechG\Bundle\SfBaseprjBundle\Extensions\MainKernel
        arguments: [@service_container, @techg.settings]       

    # TWIG EXTENSIONS        
    twig.extension.appfwKernel:
        class: TechG\Bundle\SfBaseprjBundle\Twig\Extensions\MainKernelExtension
        arguments: [@techg.kernel]
        tags:
            - { name: twig.extension }



################# EVENTS LISTER #####################
                       

    tech_g_sf_baseprj.kernel.subscriber:
        class: TechG\Bundle\SfBaseprjBundle\EventListener\TechGKernelListener
        arguments: [@techg.kernel]
        tags:
            - { name: kernel.event_subscriber }                        

    tech_g_sf_baseprj.log.subscriber:
        class: TechG\Bundle\SfBaseprjBundle\EventListener\LogListener
        arguments: [@techg.log]
        tags:
            - { name: kernel.event_subscriber }

    tech_g_sf_baseprj.debug.subscriber:
        class: TechG\Bundle\SfBaseprjBundle\EventListener\DebugListener
        arguments: [@techg.debug]
        tags:
            - { name: kernel.event_subscriber }

    tech_g_sf_baseprj.geo.subscriber:
        class: TechG\Bundle\SfBaseprjBundle\EventListener\GeocoderListener
        arguments: [@techg.geocoder]
        tags:
            - { name: kernel.event_subscriber }

    tech_g_sf_baseprj.gpanel.subscriber:
        class: TechG\Bundle\SfBaseprjBundle\EventListener\GPanelListener
        arguments: [@techg.gpanel]
        tags:
            - { name: kernel.event_subscriber }

            