parameters:
#    tech_g_sf_baseprj.example.class: TechG\SfBaseprjBundle\Example

services:
#    tech_g_sf_baseprj.example:
#        class: %tech_g_sf_baseprj.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    tech_g_sf_baseprj.kernel:
        class:     TechG\SfBaseprjBundle\Extensions\MainKernel
        arguments: [@service_container]
        
    twig.extension.appfwKernel:
        class: TechG\SfBaseprjBundle\Twig\Extensions\MainKernelExtension
        arguments: [@tech_g_sf_baseprj.kernel]
        tags:
            - { name: twig.extension }
            
    tech_g_sf_baseprj.onRequest_listener:
        class: TechG\SfBaseprjBundle\Listener\AppOnRequestListener
        arguments: [ @tech_g_sf_baseprj.kernel ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRequestEvent }              